source 'https://rubygems.org'

gem 'cucumber', '~> 2.3', '>= 2.3.3'
gem 'rspec', '~> 3.4'
gem 'httparty', '~> 0.14.0'
gem 'json', '>1.7.3'
gem 'json_spec'
gem 'rake', '~> 10.4'
gem 'require_all', '~> 1.3', '>= 1.3.3'
gem 'rspec-expectations', '~> 3.5'
gem 'json-schema', '~> 2.7'
gem 'activesupport', '>= 4.1.11'
gem 'addressable', '~> 2.4'









